events { }

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # Blazor WebAssembly requires all unknown paths to fall back to index.html
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
